import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import dynamic from "next/dynamic";

const inter = Inter({ subsets: ["latin"] });

// Dynamically import the HamburgerMenu component
const HamburgerMenu = dynamic(
  () => import("@/components/common/HamburgerMenu"),
  {
    ssr: false,
  }
);

export const metadata: Metadata = {
  title: "Film By A. Wasay",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex min-h-screen flex-col items-center justify-between p-24">
          <HamburgerMenu />
          {children}
        </main>
      </body>
    </html>
  );
}
